apiVersion: apps/v1
kind: Deployment
metadata:
  name: okhe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okhe
  template:
    metadata:
      labels:
        app: okhe
    spec:
      containers:
      - image: okteto.dev/okhe:latest
        name: okhe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "32e6989f-daf7-4538-a153-fb916c8e5ff5"
        - name: Vless_Path
          value: "/vl67hj5"
        - name: Vmess_UUID
          value: "32e6989f-daf7-4538-a153-fb916c8e5ff5"
        - name: Vmess_Path
           value: "/vl67hj5"
        - name: Share_Path
          value: "/v2link"
